// <auto-generated />
namespace sample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class createBrowser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createBrowser));
        
        string IMigrationMetadata.Id
        {
            get { return "202205280429470_createBrowser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
